example:
  property: DEV

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://database:5432/ostock_dev
    password: '0520'
  cloud:
    stream:
      kafka:
        binder:
          zkNodes: kafka1:19092
          brokers: kafka1:19092
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:9999/eureka/

