example:
  property: LOCAL
spring:
  redis:

  cloud:
    stream:
      bindings:
        inboundOrgChanges:
          destination: orgChangeTopic
          group: licensingGroup
          content-type: application/json
      kafka:
        binder:
          zkNodes: localhost:19092
          brokers: localhost:19092
  datasource:
    username: postgres
    password: '0520'
    url: jdbc:postgresql://localhost:5432/ostock_local

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/