server:
  port: 9094

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
      show-sql: 'true'
  datasource:
    testWhileIdle: 'true'
    validationQuery: SELECT 1
    platform: postgres
  cloud:
    loadbalancer:
      ribbon:
        enabled: 'false'
  database:
    driverClassName: org.postgresql.Driver

eureka:
  instance:
    preferIpAddress: 'true'
  client:
    fetchRegistry: 'true'
    registerWithEureka: 'true'

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: 'false'
  endpoint:
    health:
      enabled: true
      show-details: always

resilience4j.circuitbreaker:
  instances:
    licenseService:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 5
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException
    licensingService:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 6
      ringBufferSizeInHalfOpenState: 4
      waitDurationInOpenState: 20s
      failureRateThreshold: 60

resilience4j.ratelimiter:
  instances:
    licenseService:
      limitForPeriod: 5
      limitRefreshPeriod: 5000
      timeoutDuration: 1000ms

resilience4j.retry:
  instances:
    retryLicenseService:
      maxRetryAttempts: 5
      waitDuration: 10000
      retry-exceptions:
        - java.util.concurrent.TimeoutException

resilience4j.bulkhead:
  instances:
    bulkheadLicenseService:
      maxWaitDuration: 2ms
      maxConcurrentCalls: 20


resilience4j.thread-pool-bulkhead:
  instances:
    bulkheadLicenseService:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1

logging:
  level:
    org.springframework.web: WARN
    com.optimagrowth: DEBUG

keycloak:
  auth-server-url: http://keycloak:8080/auth
  credentials:
    secret: 5988f899-a5bf-4f76-b15f-f1cd0d2c81ba
  realm: spmia-realm
  bearer-only: 'true'
  use-resource-role-mappings: 'true'
  ssl-required: none
  resource: ostock